const translations = {
  "en": {
    "lang_txt": "Language:",
    "site_title": "Nanobody Discovery Summer School: Current & Future Methods",
    "site_title_html": "Nanobody Discovery Summer School:<br>Current & Future Methods",
    "event_date": "23–25 Sep 2026",
    "event_loc": "University of Nova Gorica",
    "event_tz": "Europe/Ljubljana timezone",
    "nav_overview": "Overview",
    "nav_programme": "Scientific talks",
    "nav_timetable": "Timetable",
    "nav_contrib": "Programme Contributions",
    "nav_reg": "Registration",
    "nav_evening": "Social Activities",
    "nav_faqs": "FAQs",
    "nav_about": "About Us",
    "nav_support": "Contact",
    "dates_title": "Dates",
    "dates_info": "23 Sep 2026 09:00 -<br>25 Sep 2026 18:00",
    "overview_h2": "Overview",
    "overview_p2": "",
    "ov_learn_h": "🔬 What You'll Learn",
    "ov_learn_1": "How nanobody libraries are constructed, characterized, and screened",
    "ov_learn_2": "Computational and Artificial Intelligence workflows to store, model, rank, design and simulate nanobody candidates",
    "ov_learn_3": "Hands-on training with phage display and wet-lab selection of antigen binders",
    "ov_who_h": "🎯 Who Should Apply?",
    "ov_who_p": "This Summer School is open to Master and PhD students with a basic background in biochemistry, structural biology, molecular biology or related fields. It's ideal for who is ready to integrate nanobody discovery into their work—computationally, experimentally or both. We will select max 10 participants based on their submitted abstract and motivation letter. Successful applicants will be notified and asked to pay a €70 registration fee (see FAQ for what is included). Free accommodation near the campus is provided from 22nd to 26th September.",
    "ov_phd_h": "🧠 Present Your Research",
    "ov_phd_p": "Each registered participant presents either their current PhD project as it relates to nanobody research or a method/idea they plan to adopt. Talks are strictly 10 minutes, followed by a moderated discussion with peers and lecturers. Participation in these sessions is a requirement of registration.",
    "ov_collab_h": "🤝 Collaboration & Networking",
    "ov_collab_p": "The program includes informal discussion rounds, dedicated networking events, and social activities designed to foster connections and future collaborations.",
    "ov_chair_h": "",
    
    "prog_h2": "Scientific talks",
    "prog_note": "The final Summer School programme will be available for download. Please note that changes may still occur.",
    "prog_desc_1": "Here we introduce the core principles of VHH library construction and display. Participants compare immune, naïve/pre-immune and synthetic library formats. They explore methods for generating diversity such as PCR amplification and CDR randomisation. The session also covers quality metrics—library size, complexity and error rates—and presents an overview of phage, yeast and ribosome display workflows.",
    "prog_desc_2": "These sessions introduce core computational workflows for nanobody discovery, beginning with repertoire profiling and homology modelling to generate initial VHH structures and assess binding via virtual panning and docking. It then progresses to de novo design strategies, showcasing machine-learning and mutational-scanning approaches for proposing novel CDR variants with enhanced stability and affinity.",
    "prog_desc_3": "These sessions focus on hands-on selection techniques for recovering antigen-specific VHHs. Participants run phage-display panning rounds, learn to adjust washing stringencies and elution methods, and compare solid-phase versus live-cell panning protocols. The session emphasises optimization at each round to maximise binder enrichment.",
    "prog_desc_4": "This session focuses on computational approaches for predicting and improving nanobody biophysical properties. Beginning with homology modelling, molecular docking and molecular dynamics, it explores how these methods can assess stability, affinity and aggregation propensity of VHHs.",
    "prog_desc_5": "Here we address the role of nanobodies in structural biology and advanced microscopy. The session begins by examining how VHHs act as crystallization chaperones and cryo-EM stabilizers, reducing conformational heterogeneity, stabilizing transient protein states and serving as fiducial markers to improve particle alignment and orientation diversity.",
    "prog_desc_6": "Each evening, early-stage researchers have the opportunity to present a concise overview of their PhD projects or novel methodological concepts in ten minutes, followed by a moderated discussion. This sessions are designed to encourage peer feedback, collaborative problem-solving and the exchange of practical insights.",
    "prog_desc_7": "Plenary keynote addresses broad perspectives on the current research landscape and future directions of nanobody science. More information to follow.",
    
    "cal_h2": "Timetable",
    "contrib_h2": "Programme Contributions",
    
    "reg_h2": "Registration",
    "reg_info": "After registration, you will receive instructions on how to pay the fee and submit an abstract.",
    "reg_cancel_info": "Please get in contact for any need of info and indications about how to reach the campus, even prior to proceed with registration. The registration can be cancelled with 100% refund if done by 1st September 2026. No refund is available for later cancellation.",
    "reg_login_req": "Account required to register",
    "reg_login_desc": "You must be logged in to register for this event.",
    "btn_login": "Login to Register",
    
    "eve_h2": "Social Activities",
    "eve_desc": "We'll share a full schedule soon, but you can already look forward to relaxed after-hours gatherings designed to bring everyone together. We will have a social dinner with all the speakers on the second day. The Summer School overlaps with <a href='https://gustidifrontiera.it/' target='_blank'>'Gusti di Frontiera'</a>, the most awaited event of the year for the city of Gorizia: as every year, along the main city streets several food and beverage enogastronomic stands will arrive from all over the world, and will be accompanied with music, fun and shows. An event to not miss!",
    
    "faq_h2": "FAQs",
    "about_h2": "About Us",
    "ab_org": "About the Organisers",
    "ab_org_desc": "This Summer School is jointly organised by members of the <a href='https://ung.si/en/research/laboratory-for-environmental-and-life-sciences/' target='_blank' rel='noopener'>Laboratory of Environmental and Life Sciences</a> at the University of Nova Gorica. We are grateful for the support of everyone who helped to make this event possible.",
    "ab_scicomm": "",
    "ab_orgcomm": "Organising Committee",
    "ab_research": "About the Research",
    "ab_research_desc": "The Ario de Marco group specialises in scalable nanobody production, focusing on efficient microbial expression systems and robust purification protocols. They have developed and refined phage display selection strategies to isolate high-affinity binders, often integrating deep sequencing to monitor selection dynamics and improve target coverage.",
    "ab_support": "Support and Funding",
    "ab_support_desc": "To be updated soon."
  },
  "it": {
    "lang_txt": "Lingua:",
    "site_title": "Nanobody Discovery Summer School: Current & Future Methods",
    "site_title_html": "Nanobody Discovery Summer School:<br>Current & Future Methods",
    "event_date": "23–25 Set 2026",
    "event_loc": "Università di Nova Gorica",
    "event_tz": "Fuso orario Europe/Ljubljana",
    "nav_overview": "Sintesi",
    "nav_programme": "Sessioni scientifiche",
    "nav_timetable": "Calendario",
    "nav_contrib": "Programme Contributions",
    "nav_reg": "Registration",
    "nav_evening": "Attività sociali",
    "nav_faqs": "FAQs",
    "nav_about": "About Us",
    "nav_support": "Contatto",
    "dates_title": "Date",
    "dates_info": "23 Set 2026 09:00 -<br>25 Set 2026 18:00",
    "overview_h2": "Sintesi",
    "overview_p2": "",
    "ov_learn_h": "🔬 Cosa imparerai",
    "ov_learn_1": "Come vengono costruite, caratterizzate e vagliate le librerie di nanobody",
    "ov_learn_2": "Flussi di lavoro computazionali e di Intelligenza Artificiale per archiviare, modellare, classificare, progettare e simulare candidati nanobody",
    "ov_learn_3": "Formazione pratica con phage display e selezione in vitro",
    "ov_who_h": "🎯 Chi dovrebbe iscriversi?",
    "ov_who_p": "Questa Summer School è aperta a studenti Master e PhD con un background di base in biochimica o campi correlati. Selezioneremo un massimo di 10 partecipanti. Quota di iscrizione: €70. Alloggio gratuito vicino al campus dal 22 al 26 settembre.",
    "ov_phd_h": "🧠 Present Your Research",
    "ov_phd_p": "Ogni partecipante dovrà presentare brevemente (10 min) il proprio progetto.",
    "ov_collab_h": "🤝 Collaborazione & Networking",
    "ov_collab_p": "Il programma include eventi sociali informali ed attività dedicate a favorire le collaborazioni future.",
    "ov_chair_h": "",
    
    "prog_h2": "Sessioni Scientifiche",
    "prog_note": "Il programma finale della Summer School sarà disponibile per il download. Sono possibili variazioni.",
    "prog_desc_1": "Introduzione ai principi della costruzione delle librerie VHH. I partecipanti esplorano i formati di libreria immuni, naive e sintetici, e le metriche di qualità.",
    "prog_desc_2": "Workflow computazionali. Profilazione di repertorio, modellistica omologica e docking per valutare il binding. Si prosegue con il design de novo tramite approcci di machine-learning.",
    "prog_desc_3": "Queste sessioni si concentrano su tecniche pratiche di selezione e panning (phage display, aggiustamento di stringenza del lavaggio).",
    "prog_desc_4": "Approcci computazionali per prevedere e migliorare le proprietà biofisiche dei nanobody (affinità, stabilità, propensione all'aggregazione).",
    "prog_desc_5": "Approfondimento sul ruolo dei nanobody in biologia strutturale e microscopia avanzata.",
    "prog_desc_6": "Sessioni in cui i giovani ricercatori presentano il proprio progetto, seguite da una discussione aperta.",
    "prog_desc_7": "Un keynote fornirà ampie prospettive sull'attuale landscape di ricerca dei nanobody.",
    
    "cal_h2": "Calendario",
    "contrib_h2": "Programme Contributions",
    
    "reg_h2": "Registrazione",
    "reg_info": "Dopo la registrazione, riceverai le istruzioni su come pagare la quota e inviare l'abstract.",
    "reg_cancel_info": "Non esitare a metterti in contatto per qualsiasi richiesta di informazioni e indicazioni su come raggiungere il campus, anche prima di procedere con la registrazione. La registrazione può essere annullata con un rimborso del 100% se effettuata entro il 1° settembre 2026. Non è disponibile alcun rimborso per cancellazioni successive.",
    "reg_login_req": "Account richiesto per iscriversi",
    "reg_login_desc": "Per iscriversi a questo evento è necessario aver effettuato il login.",
    "btn_login": "Accedi per Registrarti",
    
    "eve_h2": "Attività Sociali",
    "eve_desc": "Condivideremo presto il programma completo, ma potete già aspettarvi incontri serali rilassati. Avremo una cena sociale con tutti i relatori il secondo giorno. La Summer School coincide con <a href='https://gustidifrontiera.it/' target='_blank'>'Gusti di Frontiera'</a>, l'evento più atteso dell'anno per la città di Gorizia: come ogni anno, lungo le vie principali della città arriveranno stand enogastronomici da tutto il mondo, accompagnati da musica, divertimento e spettacoli. Un evento da non perdere!",
    
    "faq_h2": "Domande Frequenti (FAQ)",
    "about_h2": "Chi Siamo",
    "ab_org": "Informazioni sugli Organizzatori",
    "ab_org_desc": "Questa Summer School è organizzata dai membri del <a href='https://ung.si/en/research/laboratory-for-environmental-and-life-sciences/' target='_blank' rel='noopener'>Laboratory of Environmental and Life Sciences</a> della University of Nova Gorica. Siamo grati per il supporto di tutti coloro che hanno contribuito a rendere possibile questo evento.",
    "ab_scicomm": "",
    "ab_orgcomm": "Comitato Organizzatore",
    "ab_research": "Informazioni sulla Ricerca",
    "ab_research_desc": "Il gruppo Ario de Marco è specializzato nella produzione scalabile di nanobody...",
    "ab_support": "Supporto e Finanziamenti",
    "ab_support_desc": "Prossimamente."
  },
  "sl": {
    "lang_txt": "Jezik:",
    "site_title": "Nanobody Discovery Summer School: Current & Future Methods",
    "site_title_html": "Nanobody Discovery Summer School:<br>Current & Future Methods",
    "event_date": "23.–25. sep 2026",
    "event_loc": "Univerza v Novi Gorici",
    "event_tz": "Časovni pas Evropa/Ljubljana",
    "nav_overview": "Pregled",
    "nav_programme": "Znanstvena predavanja",
    "nav_timetable": "Urnik",
    "nav_contrib": "Prispevki programa",
    "nav_reg": "Registracija",
    "nav_evening": "Družabne aktivnosti",
    "nav_faqs": "Pogosta vprašanja",
    "nav_about": "O nas",
    "nav_support": "Kontakt",
    "dates_title": "Datumi",
    "dates_info": "23 sep 2026 09:00 -<br>25 sep 2026 18:00",
    "overview_h2": "Pregled",
    "overview_p2": "",
    "ov_learn_h": "🔬 Kaj se boste naučili",
    "ov_learn_1": "Kako so knjižnice nanoteeles zgrajene, karakterizirane in pregledane",
    "ov_learn_2": "Računalniški delovni tokovi in delovni tokovi umetne inteligence za shranjevanje, modeliranje, razvrščanje, načrtovanje in simulacijo kandidatov za nanoteelesa",
    "ov_learn_3": "Praktično usposabljanje s fagnim prikazom (phage display) in in vitro selekcijo",
    "ov_who_h": "🎯 Kdo naj se prijavi?",
    "ov_who_p": "Ta poletna šola je odprta za študente magistrskega in doktorskega študija. Izbrali bomo največ 10 udeležencev. Prijavnina: 70 €. Brezplačna nastanitev v bližini kampusa od 22. do 26. septembra.",
    "ov_phd_h": "🧠 Predstavite svoje raziskave",
    "ov_phd_p": "Vsak udeleženec mora na kratko (10 min) predstaviti svoj projekt.",
    "ov_collab_h": "🤝 Sodelovanje in mreženje",
    "ov_collab_p": "Program vključuje neformalna druženja in dejavnosti za spodbujanje prihodnjih sodelovanj.",
    "ov_chair_h": "",
    
    "prog_h2": "Znanstvena predavanja",
    "prog_note": "Končni program poletne šole bo na voljo za prenos. Možne so spremembe.",
    "prog_desc_1": "Uvod v načela gradnje VHH knjižnic. Udeleženci raziskujejo imunske, naivne in sintetične knjižnice ter meritve kakovosti.",
    "prog_desc_2": "Računalniški delovni tokovi. Profiliranje repertoarja, homološko modeliranje in doking (docking). Nadaljuje se z de novo oblikovanjem prek metod strojnega učenja.",
    "prog_desc_3": "Te seje se osredotočajo na praktične tehnike selekcije in paninga (prilagoditev strogosti izpiranja in protokoli).",
    "prog_desc_4": "Računalniški pristopi za napovedovanje in izboljšanje biofizikalnih lastnosti nanoteeles (afiniteta, stabilnost, nagnjenost k agregaciji).",
    "prog_desc_5": "Vloga nanoteeles v strukturni biologiji in napredni mikroskopiji.",
    "prog_desc_6": "Seje, kjer mladi raziskovalci predstavijo svoj projekt, ki jim sledi odprta razprava.",
    "prog_desc_7": "Keynote predavanje bo zagotovilo široke poglede na trenutno raziskovalno pokrajino nanoteeles.",
    
    "cal_h2": "Urnik",
    "contrib_h2": "Prispevki programa",
    
    "reg_h2": "Registracija",
    "reg_info": "Po registraciji boste prejeli navodila za plačilo prijavnine in oddajo povzetka.",
    "reg_cancel_info": "Za vsa vprašanja in informacije ter navodila o tem, kako priti do kampusa, se obrnite na nas, tudi pred registracijo. Prijavo lahko prekličete s 100-odstotnim vračilom denarja do 1. septembra 2026. Za kasnejše preklicno vračilo denarja ni na voljo.",
    "reg_login_req": "Za prijavo je potreben račun",
    "reg_login_desc": "Za prijavo na ta dogodek morate biti prijavljeni v sistem.",
    "btn_login": "Prijavite se za registracijo",
    
    "eve_h2": "Družabne aktivnosti",
    "eve_desc": "Kmalu bomo delili celoten urnik, vendar se že lahko veselite sproščenih večernih druženj. Drugi dan bomo imeli družabno večerjo z vsemi predavatelji. Poletna šola se prekriva z dogodkom <a href='https://gustidifrontiera.it/' target='_blank'>'Gusti di Frontiera'</a>, najbolj pričakovanim dogodkom leta v Gorici: kot vsako leto bodo po glavnih mestnih ulicah prispeli številni stojnice s hrano in pijačo z vsega sveta, spremljali pa jih bodo glasba, zabava in predstave. Dogodek, ki ga ne smete zamuditi!",
    
    "faq_h2": "Pogosta vprašanja (FAQ)",
    "about_h2": "O nas",
    "ab_org": "O organizatorjih",
    "ab_org_desc": "To poletno šolo organizirajo člani <a href='https://ung.si/en/research/laboratory-for-environmental-and-life-sciences/' target='_blank' rel='noopener'>Laboratorija za vede o okolju in življenju</a> na Univerzi v Novi Gorici. Hvaležni smo za podporo vsem, ki so pomagali omogočiti ta dogodek.",
    "ab_scicomm": "",
    "ab_orgcomm": "Organizacijski odbor",
    "ab_research": "O raziskavi",
    "ab_research_desc": "Skupina Ario de Marco je specializirana za razširljivo proizvodnjo nanoteeles...",
    "ab_support": "Podpora in financiranje",
    "ab_support_desc": "Kmalu bo posodobljeno."
  },
  "fr": {
    "lang_txt": "Langue:",
    "site_title": "Nanobody Discovery Summer School: Current & Future Methods",
    "site_title_html": "Nanobody Discovery Summer School:<br>Current & Future Methods",
    "event_date": "23–25 Sep 2026",
    "event_loc": "Université de Nova Gorica",
    "event_tz": "Fuseau horaire Europe/Ljubljana",
    "nav_overview": "Aperçu",
    "nav_programme": "Conférences scientifiques",
    "nav_timetable": "Emploi du temps",
    "nav_contrib": "Contributions",
    "nav_reg": "Inscription",
    "nav_evening": "Activités sociales",
    "nav_faqs": "FAQ",
    "nav_about": "À propos",
    "nav_support": "Contact",
    "dates_title": "Dates",
    "dates_info": "23 Sep 2026 09:00 -<br>25 Sep 2026 18:00",
    "overview_h2": "Aperçu",
    "overview_p2": "",
    "ov_learn_h": "🔬 Ce que vous apprendrez",
    "ov_learn_1": "Comment les bibliothèques de nanocorps sont construites et criblées",
    "ov_learn_2": "Flux de travail informatiques et d'Intelligence Artificielle pour stocker, modéliser, classer, concevoir et simuler des candidats nanocorps",
    "ov_learn_3": "Formation pratique à l'affichage sur phage et à la sélection in vitro",
    "ov_who_h": "🎯 Qui devrait postuler ?",
    "ov_who_p": "Cette École d'été est ouverte aux étudiants de Master et PhD. Nous sélectionnerons un maximum de 10 participants. Frais d'inscription : 70 €. Hébergement gratuit près du campus du 22 au 26 septembre.",
    "ov_phd_h": "🧠 Présentez votre recherche",
    "ov_phd_p": "Chaque participant présente brièvement (10 min) son projet.",
    "ov_collab_h": "🤝 Collaboration et réseau",
    "ov_collab_p": "Le programme inclut des soirées pour favoriser les collaborations.",
    "ov_chair_h": "",
    
    "prog_h2": "Conférences scientifiques",
    "prog_note": "Le programme final de l'École d'été sera disponible en téléchargement. Des modifications sont encore possibles.",
    "prog_desc_1": "Introduction à la construction de bibliothèques VHH.",
    "prog_desc_2": "Méthodes informatiques et conception de novo via l'apprentissage automatique.",
    "prog_desc_3": "Sessions pratiques sur le phage display.",
    "prog_desc_4": "Approches informatiques pour améliorer et prédire la stabilité des nanocorps.",
    "prog_desc_5": "Le rôle des nanocorps en biologie structurale.",
    "prog_desc_6": "Présentations de 10 min par les chercheurs, suivies de discussions.",
    "prog_desc_7": "Conférence plénière d'introduction.",
    
    "cal_h2": "Emploi du temps",
    "contrib_h2": "Contributions",
    
    "reg_h2": "Inscription",
    "reg_info": "Après l'inscription, vous recevrez des instructions sur la façon de payer les frais et de soumettre un résumé.",
    "reg_cancel_info": "N'hésitez pas à nous contacter pour toute demande d'information et indications sur la façon de rejoindre le campus, même avant de procéder à l'inscription. L'inscription peut être annulée avec un remboursement à 100 % si elle est effectuée avant le 1er septembre 2026. Aucun remboursement n'est possible pour une annulation ultérieure.",
    "reg_login_req": "Compte requis",
    "reg_login_desc": "Vous devez être connecté pour vous inscrire.",
    "btn_login": "Connectez-vous pour vous inscrire",
    
    "eve_h2": "Activités sociales",
    "eve_desc": "Nous partagerons bientôt un programme complet, mais vous pouvez déjà vous réjouir de rencontres détendues. Nous aurons un dîner social avec tous les intervenants le deuxième jour. L'École d'été coïncide avec <a href='https://gustidifrontiera.it/' target='_blank'>'Gusti di Frontiera'</a>, l'événement le plus attendu de l'année pour la ville de Gorizia : cet événement se déroulera dans les rues principales avec des stands du monde entier, de la musique et des spectacles. Un événement à ne pas manquer !",
    
    "faq_h2": "FAQ",
    "about_h2": "À propos",
    "ab_org": "Les organisateurs",
    "ab_org_desc": "Cette École d'été est co-organisée par les membres du <a href='https://ung.si/en/research/laboratory-for-environmental-and-life-sciences/' target='_blank' rel='noopener'>Laboratoire des sciences de l'environnement et de la vie</a> de l'Université de Nova Gorica. Nous sommes reconnaissants du soutien de tous ceux qui ont contribué à rendre cet événement possible.",
    "ab_scicomm": "",
    "ab_orgcomm": "Comité d'organisation",
    "ab_research": "Recherche",
    "ab_research_desc": "Le groupe Ario de Marco se spécialise dans la production de nanocorps...",
    "ab_support": "Soutien et financement",
    "ab_support_desc": "À mettre à jour bientôt."
  },
  "es": {
    "lang_txt": "Idioma:",
    "site_title": "Nanobody Discovery Summer School: Current & Future Methods",
    "site_title_html": "Nanobody Discovery Summer School:<br>Current & Future Methods",
    "event_date": "23–25 Sep 2026",
    "event_loc": "Universidad de Nova Gorica",
    "event_tz": "Zona horaria Europe/Ljubljana",
    "nav_overview": "Resumen",
    "nav_programme": "Sesiones científicas",
    "nav_timetable": "Horario",
    "nav_contrib": "Contribuciones",
    "nav_reg": "Registro",
    "nav_evening": "Actividades sociales",
    "nav_faqs": "Preguntas Frecuentes",
    "nav_about": "Acerca de",
    "nav_support": "Contacto",
    "dates_title": "Fechas",
    "dates_info": "23 Sep 2026 09:00 -<br>25 Sep 2026 18:00",
    "overview_h2": "Resumen",
    "overview_p2": "",
    "ov_learn_h": "🔬 Qué aprenderás",
    "ov_learn_1": "Cómo se construyen, caracterizan y examinan las bibliotecas de nanocuerpos",
    "ov_learn_2": "Flujos de trabajo computacionales y de Inteligencia Artificial para almacenar, modelar, clasificar, diseñar y simular candidatos a nanocuerpos",
    "ov_learn_3": "Formación práctica con presentación de fagos y selección in vitro",
    "ov_who_h": "🎯 ¿Quién debería postularse?",
    "ov_who_p": "Esta Escuela de Verano está abierta a estudiantes de Máster y PhD. Seleccionaremos un máximo de 10 participantes. Precio de la inscripción: 70 €. Alojamiento gratuito cerca del campus del 22 al 26 de septiembre.",
    "ov_phd_h": "🧠 Presenta tu investigación",
    "ov_phd_p": "Cada participante presentará brevemente (10 min) su proyecto.",
    "ov_collab_h": "🤝 Colaboración y Networking",
    "ov_collab_p": "El programa incluye veladas informales y actividades para fomentar futuras colaboraciones.",
    "ov_chair_h": "",
    "prog_h2": "Sesiones científicas",
    "prog_note": "El programa final de la Escuela de Verano estará disponible para su descarga. Son posibles variaciones.",
    "prog_desc_1": "Introducción a los principios de construcción de bibliotecas VHH.",
    "prog_desc_2": "Flujos de trabajo computacionales y diseño de novo mediante aprendizaje automático.",
    "prog_desc_3": "Sesiones prácticas sobre técnicas de selección con phage display.",
    "prog_desc_4": "Enfoques computacionales para predecir y mejorar las propiedades biofísicas de los nanocuerpos.",
    "prog_desc_5": "El papel de los nanocuerpos en biología estructural.",
    "prog_desc_6": "Sesiones donde los investigadores presentan su proyecto (10 min), seguido de una discusión abierta.",
    "prog_desc_7": "Charla magistral que ofrece una amplia visión del panorama actual de investigación en nanocuerpos.",
    "cal_h2": "Horario",
    "contrib_h2": "Contribuciones",
    "reg_h2": "Registro",
    "reg_info": "Después de registrarse, recibirá instrucciones sobre cómo pagar la tarifa y enviar un resumen.",
    "reg_cancel_info": "No dude en ponerse en contacto con nosotros para cualquier información o indicaciones sobre cómo llegar al campus, incluso antes de proceder con el registro. El registro se puede cancelar con el 100 % de reembolso si se realiza antes del 1 de septiembre de 2026. No habrá reembolso para cancelaciones posteriores.",
    "reg_login_req": "Se requiere cuenta para registrarse",
    "reg_login_desc": "Debes iniciar sesión para inscribirte en este evento.",
    "btn_login": "Inicia sesión para registrarte",
    "eve_h2": "Actividades sociales",
    "eve_desc": "Pronto compartiremos el programa completo, pero ya podéis esperar encuentros relajados. Tendremos una cena social con todos los ponentes el segundo día. La Escuela de Verano coincide con <a href='https://gustidifrontiera.it/' target='_blank'>'Gusti di Frontiera'</a>, el evento más esperado del año para la ciudad de Gorizia: este evento se celebrará en las calles principales con puestos de comida de todo el mundo, música y espectáculos. ¡Un evento que no te puedes perder!",
    "faq_h2": "Preguntas Frecuentes",
    "about_h2": "Acerca de nosotros",
    "ab_org": "Los organizadores",
    "ab_org_desc": "Esta Escuela de Verano está organizada conjuntamente por miembros del <a href='https://ung.si/en/research/laboratory-for-environmental-and-life-sciences/' target='_blank' rel='noopener'>Laboratorio de Ciencias Ambientales y de la Vida</a> de la Universidad de Nova Gorica. Agradecemos el apoyo de todos los que ayudaron a hacer posible este evento.",
    "ab_scicomm": "",
    "ab_orgcomm": "Comité Organizador",
    "ab_research": "Sobre la Investigación",
    "ab_research_desc": "El grupo de Ario de Marco se especializa en la producción escalable de nanocuerpos...",
    "ab_support": "Apoyo y Financiación",
    "ab_support_desc": "Se actualizará pronto."
  },
  "de": {
    "lang_txt": "Sprache:",
    "site_title": "Nanobody Discovery Summer School: Current & Future Methods",
    "site_title_html": "Nanobody Discovery Summer School:<br>Current & Future Methods",
    "event_date": "23.–25. Sep. 2026",
    "event_loc": "Universität Nova Gorica",
    "event_tz": "Zeitzone Europe/Ljubljana",
    "nav_overview": "Überblick",
    "nav_programme": "Wissenschaftliche Vorträge",
    "nav_timetable": "Zeitplan",
    "nav_contrib": "Beiträge",
    "nav_reg": "Registrierung",
    "nav_evening": "Soziale Aktivitäten",
    "nav_faqs": "FAQ",
    "nav_about": "Über uns",
    "nav_support": "Kontakt",
    "dates_title": "Termine",
    "dates_info": "23. Sep. 2026 09:00 -<br>25. Sep. 2026 18:00",
    "overview_h2": "Überblick",
    "overview_p2": "",
    "ov_learn_h": "🔬 Was Sie lernen werden",
    "ov_learn_1": "Wie Nanobody-Bibliotheken konstruiert, charakterisiert und gescreent werden",
    "ov_learn_2": "Computergestützte Workflows und Workflows der Künstlichen Intelligenz zum Speichern, Modellieren, Einstufen, Entwerfen und Simulieren von Nanobody-Kandidaten",
    "ov_learn_3": "Praktische Schulung zu Phage Display und In-Vitro-Selektion",
    "ov_who_h": "🎯 Wer sollte sich bewerben?",
    "ov_who_p": "Diese Sommerschule richtet sich an Master- und Doktoratsstudierende. Wir werden maximal 10 Teilnehmer auswählen. Teilnahmegebühr: 70 €. Kostenlose Unterkunft in Campusnähe vom 22. bis 26. September.",
    "ov_phd_h": "🧠 Präsentieren Sie Ihre Forschung",
    "ov_phd_p": "Jeder Teilnehmer präsentiert kurz (10 Min) sein Projekt.",
    "ov_collab_h": "🤝 Zusammenarbeit & Networking",
    "ov_collab_p": "Das Programm umfasst informelle Abendveranstaltungen, um künftige Kooperationen zu fördern.",
    "ov_chair_h": "",
    "prog_h2": "Wissenschaftliche Vorträge",
    "prog_note": "Das endgültige Programm der Sommerschule wird zum Download bereitstehen. Änderungen vorbehalten.",
    "prog_desc_1": "Einführung in die Prinzipien der VHH-Bibliothekskonstruktion.",
    "prog_desc_2": "Computergestützte Workflows und De-novo-Design durch maschinelles Lernen.",
    "prog_desc_3": "Praktische Sitzungen zum Phage Display und Selektionstechniken.",
    "prog_desc_4": "Ansätze zur Vorhersage und Verbesserung der biophysikalischen Eigenschaften von Nanobodies.",
    "prog_desc_5": "Die Rolle von Nanobodies in der Strukturbiologie.",
    "prog_desc_6": "Sitzungen, in denen Forscher ihr Projekt vorstellen (10 Min), gefolgt von Diskussionen.",
    "prog_desc_7": "Keynote-Vortrag mit umfassenden Perspektiven zur aktuellen Forschung.",
    "cal_h2": "Zeitplan",
    "contrib_h2": "Beiträge",
    "reg_h2": "Registrierung",
    "reg_info": "Nach der Registrierung erhalten Sie Anweisungen zur Zahlung der Gebühr und zur Einreichung eines Abstracts.",
    "reg_cancel_info": "Bitte setzen Sie sich für alle Informationswünsche und Hinweise zur Anreise zum Campus mit uns in Verbindung, auch vor der Registrierung. Die Registrierung kann bei einer Stornierung bis zum 1. September 2026 zu 100 % erstattet werden. Bei einer späteren Stornierung ist keine Rückerstattung möglich.",
    "reg_login_req": "Konto erforderlich",
    "reg_login_desc": "Sie müssen eingeloggt sein, um sich für diese Veranstaltung zu registrieren.",
    "btn_login": "Anmelden zur Registrierung",
    "eve_h2": "Soziale Aktivitäten",
    "eve_desc": "Wir werden bald einen vollständigen Zeitplan veröffentlichen, aber Sie können sich schon jetzt auf entspannte Abende freuen. Am zweiten Tag werden wir ein gemeinsames Abendessen mit allen Referenten haben. Die Sommerschule überschneidet sich mit <a href='https://gustidifrontiera.it/' target='_blank'>'Gusti di Frontiera'</a>, dem am sehnlichsten erwarteten Ereignis des Jahres für die Stadt Gorizia: Dieses Ereignis findet in den Hauptstraßen der Stadt statt, mit Ständen aus der ganzen Welt, Musik und Shows. Ein Ereignis, das man nicht verpassen sollte!",
    "faq_h2": "Häufig gestellte Fragen (FAQ)",
    "about_h2": "Über uns",
    "ab_org": "Die Organisatoren",
    "ab_org_desc": "Diese Sommerschule wird gemeinsam von Mitgliedern des <a href='https://ung.si/en/research/laboratory-for-environmental-and-life-sciences/' target='_blank' rel='noopener'>Labors für Umwelt- und Lebenswissenschaften</a> der Universität Nova Gorica organisiert. Wir sind dankbar für die Unterstützung aller, die dazu beigetragen haben, diese Veranstaltung zu ermöglichen.",
    "ab_scicomm": "",
    "ab_orgcomm": "Organisationskomitee",
    "ab_research": "Forschung",
    "ab_research_desc": "Die Gruppe Ario de Marco ist auf die skalierbare Produktion von Nanobodies spezialisiert...",
    "ab_support": "Unterstützung und Finanzierung",
    "ab_support_desc": "Wird bald aktualisiert."
  }
};

function changeLanguage(lang) {
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(element => {
    const key = element.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      element.innerHTML = translations[lang][key];
    }
  });
}

// Initial default to English
changeLanguage('en');
